### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by dayanare** [Adalab/modulo-2-evaluacion-intermedia-jnataliaramirez#1]
Really cool job @jnataliaramirez  !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Enable Strict mode by writing 'use strict' at the beginning of the js document.
- [x] Check if the number is less than 1 or greater than 100.
- [x] Remove debugger and other unnecessary code

### HTML

- [x] Add form
- [x] Add HTML elements for the game: title, label, input, button, space for feedback (`div`, `p`) and number of trials.
- [x] Use a `label` to define the content of the input.
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input.
- [x] Use placeholder attribute instead of value one to show a field's hint.
- [x] Use placeholder.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by jnataliaramirez** [comment]
Hello Dayana
I fixed my issues.
Thanks for your attention.
